import mongoose from 'mongoose'
const allergenSchema = new mongoose.Schema({
    name: {
      type: String,
    },
    description: {
      type: String,
    }
  });

  const additiveSchema = new mongoose.Schema({
    name: {
      type: String,
    },
    description: {
      type: String,
    },
  });

  const ingredientSchema = new mongoose.Schema({
    name: {
      type: String,
    },
    description: {
      type: String,
    },
  });

const productSchema = new mongoose.Schema({
    code:{
        type:Number,
        required:true
    },
    url: String,
    product_name: String,
    generic_name: String,
    quantity: String,
    brands: String,
    categories: String,
    ingredients_text: String,
    ingredients_analysis_tags: String,
    allergens: String,
    traces: String,
    additives_n: Number,
    additives_en: String,
    pnns_groups_1: String,
    pnns_groups_2: String,
    product_quantity: Number,
    main_category_en: String,
    image_url: String,
    image_small_url: String,
    image_ingredients_url: String,
    image_ingredients_small_url: String,
    image_nutrition_url: String,
    image_nutrition_small_url: String,
    energy_kcal_100g: Number,
    energy_100g: Number,
    energy_from_fat_100g: Number,
    fat_100g: Number,
    saturated_fat_100g: Number,
    butyric_acid_100g: Number,
    caproic_acid_100g: Number,
    caprylic_acid_100g: Number,
    capric_acid_100g: Number,
    lauric_acid_100g: Number,
    myristic_acid_100g: Number,
    palmitic_acid_100g: Number,
    stearic_acid_100g: Number,
    arachidic_acid_100g: Number,
    behenic_acid_100g: Number,
    lignoceric_acid_100g: Number,
    cerotic_acid_100g: Number,
    montanic_acid_100g: Number,
    melissic_acid_100g: Number,
    unsaturated_fat_100g: Number,
    monounsaturated_fat_100g: Number,
    omega_9_fat_100g: Number,
    polyunsaturated_fat_100g: Number,
    omega_3_fat_100g: Number,
    omega_6_fat_100g: Number,
    alpha_linolenic_acid_100g: Number,
    eicosapentaenoic_acid_100g: Number,
    docosahexaenoic_acid_100g: Number,
    linoleic_acid_100g: Number,
    arachidonic_acid_100g: Number,
    gamma_linolenic_acid_100g: Number,
    dihomo_gamma_linolenic_acid_100g: Number,
    oleic_acid_100g: Number,
    elaidic_acid_100g: Number,
    gondoic_acid_100g: Number,
    mead_acid_100g: Number,
    erucic_acid_100g: Number,
    nervonic_acid_100g: Number,
    trans_fat_100g: Number,
    cholesterol_100g: Number,
    carbohydrates_100g: Number,
    sugars_100g: Number,
    added_sugars_100g: Number,
    sucrose_100g: Number,
    glucose_100g: Number,
    fructose_100g: Number,
    lactose_100g: Number,
    maltose_100g: Number,
    maltodextrins_100g: Number,
    starch_100g: Number,
    polyols_100g: Number,
    erythritol_100g: Number,
    fiber_100g: Number,
    soluble_fiber_100g: Number,
    insoluble_fiber_100g: Number,
    proteins_100g: Number,
    casein_100g: Number,
    serum_proteins_100g: Number,
    nucleotides_100g: Number,
    salt_100g: Number,
    added_salt_100g: Number,
    sodium_100g: Number,
    alcohol_100g: Number,
    vitamin_a_100g: Number,
    beta_carotene_100g: Number,
    vitamin_d_100g: Number,
    vitamin_e_100g: Number,
    vitamin_k_100g: Number,
    vitamin_c_100g: Number,
    vitamin_b1_100g: Number,
    vitamin_b2_100g: Number,
    vitamin_pp_100g: Number,
    vitamin_b6_100g: Number,
    vitamin_b9_100g: Number,
    folates_100g: Number,
    vitamin_b12_100g: Number,
    biotin_100g: Number,
    pantothenic_acid_100g: Number,
    silica_100g: Number,
    bicarbonate_100g: Number,
    potassium_100g: Number,
    chloride_100g: Number,
    calcium_100g: Number,
    phosphorus_100g: Number,
    iron_100g: Number,
    magnesium_100g: Number,
    zinc_100g: Number,
    copper_100g: Number,
    manganese_100g: Number,
    fluoride_100g: Number,
    selenium_100g: Number,
    chromium_100g: Number,
    molybdenum_100g: Number,
    iodine_100g: Number,
    caffeine_100g: Number,
    taurine_100g: Number,
    ph_100g: Number,
    fruits_vegetables_nuts_100g: Number,
    fruits_vegetables_nuts_dried_100g: Number,
    fruits_vegetables_nuts_estimate_100g: Number,
    fruits_vegetables_nuts_estimate_from_ingredients_100g: Number,
    collagen_meat_protein_ratio_100g: Number,
    cocoa_100g: Number,
    chlorophyl_100g: Number,
    carbon_footprint_100g: Number,
    carbon_footprint_from_meat_or_fish_100g: Number,
    glycemic_index_100g: Number,
    water_hardness_100g: Number,
    choline_100g: Number,
    phylloquinone_100g: Number,
    beta_glucan_100g: Number,
    inositol_100g: Number,
    carnitine_100g: Number,
    sulphate_100g: Number,
    nitrate_100g: Number,
    acidity_100g: Number,
    category: String,
    product_category:String,
    HealthStarRating: mongoose.Schema.Types.Mixed,
    HSRTotalPoints: mongoose.Schema.Types.Mixed,
    nutriscore_score_final: mongoose.Schema.Types.Mixed,
    nutriscore_grade_final: String,
    allergens_info:[allergenSchema],
    additives_info:[additiveSchema],
    ingredients_info:[ingredientSchema],
    isNewProduct:Boolean
});

export const products = mongoose.model('productinfo', productSchema);
